-- Create parts_requests table for parts inventory
CREATE TABLE IF NOT EXISTS parts_requests (
    id SERIAL PRIMARY KEY,
    sd_invoice_number VARCHAR(20),
    request_id INTEGER,
    requested_qty INTEGER DEFAULT 1,
    requested_date DATE,
    requesting_tech VARCHAR(10),
    customer_name VARCHAR(200),
    machine_type VARCHAR(100),
    machine_make VARCHAR(50),
    machine_model VARCHAR(50),
    machine_serial VARCHAR(100),
    part_description TEXT,
    request_instructions TEXT,
    request_notes TEXT,
    part_number VARCHAR(100),
    vendor VARCHAR(100),
    vendor_inquiry_date DATE,
    contact_person VARCHAR(100),
    contact_method VARCHAR(50),
    quoted_wholesale DECIMAL(10,2),
    quoted_retail DECIMAL(10,2),
    availability VARCHAR(100),
    order_instructions TEXT,
    po_number VARCHAR(50),
    date_order_confirmed DATE,
    date_shipment_expected DATE,
    date_received DATE,
    invoice_cost DECIMAL(10,2),
    purchase_invoice_number VARCHAR(50),
    sell_for_price DECIMAL(10,2),
    hold_location VARCHAR(100),
    purchase_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
); 